package liste;

public class ApplyingListe extends Liste {

    public ApplyingListe() {
        super();
    }

    @Override
    public void fillEnListe() {
        addListToEn("appendix");
        addListToEn("applicant","candidate");
        addListToEn("assets");
        addListToEn("be entitled to");
        addListToEn("blue collar worker");
        addListToEn("board");
        addListToEn("board of directors");
        addListToEn("bonus");
        addListToEn("buyer");
        addListToEn("call in sick");
        addListToEn("carry out");
        addListToEn("CEO");
        addListToEn("chairman","chairwoman","chairperson");
        addListToEn("civil servant");
        addListToEn("classified ads");
        addListToEn("clerical");
        addListToEn("clerk");
        addListToEn("competitor");
        addListToEn("credentials");
        addListToEn("credit");
        addListToEn("day off");
        addListToEn("deal");
        addListToEn("dismiss");
        addListToEn("downsize");
        addListToEn("draft project");
        addListToEn("earn");
        addListToEn("earnings");
        addListToEn("enrollment");
        addListToEn("executive");
        addListToEn("fire");
        addListToEn("fiscal year");
        addListToEn("head");
        addListToEn("headhunter");
        addListToEn("head-office","headquarters");
        addListToEn("health care package");
        addListToEn("help wanted ad");
        addListToEn("hire");
        addListToEn("incentive");
        addListToEn("income");
        addListToEn("intern","trainee");
        addListToEn("internship","job placement");
        addListToEn("investor");
        addListToEn("job hunter");
        addListToEn("lawsuit");
        addListToEn("lay off");
        addListToEn("leave");
        addListToEn("liabilities");
        addListToEn("lunch break");
        addListToEn("margin");
        addListToEn("notice");
        addListToEn("occupation");
        addListToEn("officer");
        addListToEn("operating costs");
        addListToEn("overtime");
        addListToEn("parent company");
        addListToEn("pay check");
        addListToEn("pay scale");
        addListToEn("payslip");
        addListToEn("perk");
        addListToEn("position");
        addListToEn("pregnancy");
        addListToEn("R&D");
        addListToEn("raise");
        addListToEn("redundancy");
        addListToEn("regulations");
        addListToEn("resign");
        addListToEn("resume");
        addListToEn("retire");
        addListToEn("scheme");
        addListToEn("screening");
        addListToEn("seniority");
        addListToEn("sick leave");
        addListToEn("skill");
        addListToEn("skilled");
        addListToEn("staff");
        addListToEn("standard");
        addListToEn("stockholder");
        addListToEn("strike");
        addListToEn("take on");
        addListToEn("takeover");
        addListToEn("takeover bid");
        addListToEn("temp");
        addListToEn("terminated");
        addListToEn("training");
        addListToEn("turnover");
        addListToEn("union");
        addListToEn("vacancy");
        addListToEn("vacant");
        addListToEn("vacation");
        addListToEn("wage");
        addListToEn("work load");
        addListToEn("workplace");
        addListToEn("workshop");
    }

    @Override
    public void fillFrListe() {
        addListToFr("annexe");
        addListToFr("candidat");
        addListToFr("actif");
        addListToFr("avoir droit a");
        addListToFr("col bleu");
        addListToFr("conseil");
        addListToFr("conseil d'administration");
        addListToFr("prime");
        addListToFr("acheteur");
        addListToFr("informer qu'on est malade");
        addListToFr("effectuer");
        addListToFr("PDG");
        addListToFr("president");
        addListToFr("fonctionnaire");
        addListToFr("petite annonces");
        addListToFr("de bureau");
        addListToFr("employe de bureau");
        addListToFr("concurrent");
        addListToFr("titres","diplomes");
        addListToFr("honneur","merites");
        addListToFr("jour de conge");
        addListToFr("affaire","negociation");
        addListToFr("licencier");
        addListToFr("reduire le personnel");
        addListToFr("avant-projet");
        addListToFr("gagner");
        addListToFr("resultats","gains");
        addListToFr("inscription");
        addListToFr("cadre");
        addListToFr("renvoyer");
        addListToFr("exercice");
        addListToFr("chef");
        addListToFr("chasseur de tetes");
        addListToFr("siege social");
        addListToFr("mutuelle de sante");
        addListToFr("annonce de recrutement");
        addListToFr("embaucher");
        addListToFr("motivation","prime");
        addListToFr("revenu");
        addListToFr("stagiaire");
        addListToFr("stage");
        addListToFr("investisseur");
        addListToFr("demandeur d'emploi");
        addListToFr("proces");
        addListToFr("licencier");
        addListToFr("conge");
        addListToFr("passif","responsabilite");
        addListToFr("pause dejeuner");
        addListToFr("marge");
        addListToFr("preavis");
        addListToFr("emploi");
        addListToFr("dirigeant");
        addListToFr("couts de fonctionnement");
        addListToFr("heures supplementaires");
        addListToFr("societe mere");
        addListToFr("paye","cheque de salaire");
        addListToFr("echelle des salaires");
        addListToFr("fiche de paye");
        addListToFr("avantage en nature");
        addListToFr("poste");
        addListToFr("grossesse");
        addListToFr("recherche et developpement");
        addListToFr("augmentation");
        addListToFr("mise au chomage");
        addListToFr("reglement");
        addListToFr("demissionner");
        addListToFr("CV");
        addListToFr("prendre sa retraite");
        addListToFr("systeme");
        addListToFr("selection");
        addListToFr("anciennete");
        addListToFr("conge maladie");
        addListToFr("competence","qualification");
        addListToFr("qualifie");
        addListToFr("personnel");
        addListToFr("norme");
        addListToFr("actionnaire");
        addListToFr("greve");
        addListToFr("embaucher");
        addListToFr("prise de controle","rachat");
        addListToFr("OPA");
        addListToFr("interimaire","faire de l'interim");
        addListToFr("resilie");
        addListToFr("stagiaire");
        addListToFr("formation");
        addListToFr("chiffre d'affaires");
        addListToFr("syndicat");
        addListToFr("poste a pourvoir");
        addListToFr("vacant");
        addListToFr("vacances");
        addListToFr("salaire horaire");
        addListToFr("charge de travail");
        addListToFr("lieu de travail");
        addListToFr("atelier");
    }
}
