package liste;

public class MiscellaneousListe extends Liste {

    public MiscellaneousListe() {
        super();
    }

    @Override
    public void fillEnListe() {
        addListToEn("above");
        addListToEn("among");
        addListToEn("available");
        addListToEn("below");
        addListToEn("beneath");
        addListToEn("beside");
        addListToEn("boundaries");
        addListToEn("broad");
        addListToEn("by");
        addListToEn("cancel");
        addListToEn("climb");
        addListToEn("close to");
        addListToEn("crane");
        addListToEn("crop");
        addListToEn("demanding");
        addListToEn("downward");
        addListToEn("early");
        addListToEn("earth");
        addListToEn("entertainment");
        addListToEn("fall");
        addListToEn("fill");
        addListToEn("flag");
        addListToEn("forward");
        addListToEn("gather");
        addListToEn("handle");
        addListToEn("hardly");
        addListToEn("hill");
        addListToEn("huge");
        addListToEn("implement");
        addListToEn("issue");
        addListToEn("lake");
        addListToEn("law");
        addListToEn("library");
        addListToEn("lift");
        addListToEn("location");
        addListToEn("loud");
        addListToEn("map");
        addListToEn("movie theatre");
        addListToEn("nap");
        addListToEn("noon");
        addListToEn("notice");
        addListToEn("occur");
        addListToEn("off");
        addListToEn("panel");
        addListToEn("prize");
        addListToEn("provided");
        addListToEn("purpose");
        addListToEn("quarter");
        addListToEn("rating");
        addListToEn("rental");
        addListToEn("respondent");
        addListToEn("rest");
        addListToEn("resume");
        addListToEn("seldom");
        addListToEn("shore");
        addListToEn("shortcut");
        addListToEn("site");
        addListToEn("soccer");
        addListToEn("spoil");
        addListToEn("spring");
        addListToEn("stack");
        addListToEn("stand");
        addListToEn("stand up");
        addListToEn("standstill");
        addListToEn("terms");
        addListToEn("toward");
        addListToEn("town hall");
        addListToEn("upcoming");
        addListToEn("upset");
        addListToEn("wave");
        addListToEn("weigh");
        addListToEn("weight");
    }

    @Override
    public void fillFrListe() {
        addListToFr("au-dessus de");
        addListToFr("parmi");
        addListToFr("disponible");
        addListToFr("en dessous de");
        addListToFr("en dessous de");
        addListToFr("a cote de");
        addListToFr("frontieres");
        addListToFr("large");
        addListToFr("pres de");
        addListToFr("annuler");
        addListToFr("monter","gravir");
        addListToFr("pres de");
        addListToFr("grue");
        addListToFr("recolte");
        addListToFr("exigeant");
        addListToFr("vers le bas");
        addListToFr("tot");
        addListToFr("Terre");
        addListToFr("divertissement");
        addListToFr("automne");
        addListToFr("remplir");
        addListToFr("drapeau");
        addListToFr("vers l'avant");
        addListToFr("rassembler");
        addListToFr("poignee","manipuler");
        addListToFr("a peine");
        addListToFr("colline");
        addListToFr("enorme");
        addListToFr("mettre en place");
        addListToFr("numero","probleme");
        addListToFr("lac");
        addListToFr("droit","loi");
        addListToFr("bibliotheque");
        addListToFr("soulever");
        addListToFr("emplacement");
        addListToFr("a voix haute","fort");
        addListToFr("carte");
        addListToFr("cinema");
        addListToFr("sieste");
        addListToFr("midi");
        addListToFr("preavis","remarquer");
        addListToFr("se produire");
        addListToFr("eteint","a l'ecart de");
        addListToFr("panneau","groupe");
        addListToFr("prix","recompense");
        addListToFr("du moment que");
        addListToFr("but");
        addListToFr("trimestre");
        addListToFr("note","jugement");
        addListToFr("de location");
        addListToFr("personne sondee");
        addListToFr("repos");
        addListToFr("reprendre","recommencer");
        addListToFr("rarement");
        addListToFr("rive","bord");
        addListToFr("raccourci");
        addListToFr("site");
        addListToFr("football");
        addListToFr("gacher");
        addListToFr("printemps");
        addListToFr("pile","empiler");
        addListToFr("etre debout");
        addListToFr("se lever");
        addListToFr("arret","immobilisation");
        addListToFr("conditions");
        addListToFr("vers");
        addListToFr("mairie");
        addListToFr("imminent","a venir");
        addListToFr("bouleverser","bouleversé");
        addListToFr("faire signe");
        addListToFr("peser");
        addListToFr("poids");
    }
}
