package liste;

public class OfficeLifeListe extends Liste {

    public OfficeLifeListe() {
        super();
    }

    @Override
    public void fillEnListe() {
        addListToEn("agenda");
        addListToEn("assignment");
        addListToEn("attached");
        addListToEn("bid");
        addListToEn("binder");
        addListToEn("board");
        addListToEn("bold");
        addListToEn("booklet");
        addListToEn("briefcase");
        addListToEn("cancel");
        addListToEn("carry out");
        addListToEn("cartridge");
        addListToEn("CEO");
        addListToEn("chart");
        addListToEn("commercial");
        addListToEn("competitor");
        addListToEn("complete");
        addListToEn("corporate");
        addListToEn("data");
        addListToEn("data processing");
        addListToEn("deadline");
        addListToEn("delete");
        addListToEn("department");
        addListToEn("desk");
        addListToEn("dial");
        addListToEn("directory");
        addListToEn("dismiss");
        addListToEn("draft");
        addListToEn("drawer");
        addListToEn("earnings");
        addListToEn("entitled to");
        addListToEn("executive");
        addListToEn("expenditures");
        addListToEn("extension");
        addListToEn("fan");
        addListToEn("feasible");
        addListToEn("file");
        addListToEn("flyer");
        addListToEn("folder");
        addListToEn("font");
        addListToEn("form");
        addListToEn("forward");
        addListToEn("glue");
        addListToEn("guidelines");
        addListToEn("handling");
        addListToEn("head");
        addListToEn("incentive");
        addListToEn("income");
        addListToEn("inquiry");
        addListToEn("intern","trainee");
        addListToEn("internship","job placement");
        addListToEn("IT");
        addListToEn("jam");
        addListToEn("key");
        addListToEn("keyboard");
        addListToEn("laptop");
        addListToEn("launch");
        addListToEn("layout");
        addListToEn("leave");
        addListToEn("load");
        addListToEn("margin");
        addListToEn("marketplace");
        addListToEn("mixed up");
        addListToEn("monitor");
        addListToEn("mouse pad");
        addListToEn("name tag");
        addListToEn("network");
        addListToEn("notepad");
        addListToEn("notice");
        addListToEn("overdue");
        addListToEn("overnight mail");
        addListToEn("pad of paper");
        addListToEn("parent company");
        addListToEn("pick up");
        addListToEn("position");
        addListToEn("postpone");
        addListToEn("printer");
        addListToEn("process");
        addListToEn("purchase");
        addListToEn("raise");
        addListToEn("receiver");
        addListToEn("record");
        addListToEn("resign");
        addListToEn("retire");
        addListToEn("scheme");
        addListToEn("screen");
        addListToEn("sheet");
        addListToEn("shipment");
        addListToEn("skill");
        addListToEn("slide");
        addListToEn("software");
        addListToEn("software program");
        addListToEn("sort");
        addListToEn("spreadsheet");
        addListToEn("staff");
        addListToEn("staple");
        addListToEn("stationery");
        addListToEn("store");
        addListToEn("supplies");
        addListToEn("supply room");
        addListToEn("survey");
        addListToEn("switchboard");
        addListToEn("take on");
        addListToEn("takeover bid");
        addListToEn("task");
        addListToEn("temp");
        addListToEn("training program");
        addListToEn("transfer");
        addListToEn("trash");
        addListToEn("trend");
        addListToEn("trial order");
        addListToEn("triplicate");
        addListToEn("turnover");
        addListToEn("type");
        addListToEn("typing error");
        addListToEn("update");
        addListToEn("vacancy");
        addListToEn("vacant");
        addListToEn("vacation");
        addListToEn("wage");
        addListToEn("word processing");
        addListToEn("wrap");
    }

    @Override
    public void fillFrListe() {
        addListToFr("ordre du jour");
        addListToFr("travail a accomplir","mission","tache");
        addListToFr("joint");
        addListToFr("offre");
        addListToFr("classeur");
        addListToFr("conseil");
        addListToFr("en gras");
        addListToFr("fascicule");
        addListToFr("porte-document");
        addListToFr("annuler");
        addListToFr("effectuer");
        addListToFr("cartouche");
        addListToFr("PDG");
        addListToFr("graphique","tableau");
        addListToFr("spot publicitaire");
        addListToFr("concurrent");
        addListToFr("achever");
        addListToFr("d'entreprise");
        addListToFr("donnees");
        addListToFr("traitement de donnees");
        addListToFr("date limite");
        addListToFr("effacer");
        addListToFr("service");
        addListToFr("bureau");
        addListToFr("composer");
        addListToFr("annuaire");
        addListToFr("renvoyer");
        addListToFr("brouillon");
        addListToFr("tiroir");
        addListToFr("gains");
        addListToFr("ayant droit a");
        addListToFr("cadre");
        addListToFr("depenses");
        addListToFr("poste telephonique");
        addListToFr("ventilateur");
        addListToFr("faisable");
        addListToFr("classeur","classer");
        addListToFr("prospectus");
        addListToFr("chemise");
        addListToFr("police d'ecriture");
        addListToFr("formulaire");
        addListToFr("transmettre");
        addListToFr("colle");
        addListToFr("instructions");
        addListToFr("manutention");
        addListToFr("chef");
        addListToFr("motivation","prime");
        addListToFr("revenu");
        addListToFr("demande de renseignements");
        addListToFr("stagiaire");
        addListToFr("stage");
        addListToFr("informatique");
        addListToFr("bourrage de papier");
        addListToFr("touche");
        addListToFr("clavier");
        addListToFr("ordinateur portable");
        addListToFr("lancement","lancer");
        addListToFr("presentation d'un document");
        addListToFr("conge");
        addListToFr("chargement","charger");
        addListToFr("marge");
        addListToFr("part de marche");
        addListToFr("melange");
        addListToFr("moniteur");
        addListToFr("tapis de souris");
        addListToFr("badge nominatif");
        addListToFr("reseau");
        addListToFr("bloc-notes");
        addListToFr("preavis");
        addListToFr("en retard");
        addListToFr("courrier qui arrive le lendemain");
        addListToFr("bloc de papier");
        addListToFr("societe-mere");
        addListToFr("ramasser","aller chercher");
        addListToFr("poste");
        addListToFr("retarder");
        addListToFr("imprimante");
        addListToFr("traiter");
        addListToFr("acheter");
        addListToFr("augmentation","augmenter");
        addListToFr("combine telephonique");
        addListToFr("archive");
        addListToFr("demissionner");
        addListToFr("prendre sa retraite");
        addListToFr("systeme");
        addListToFr("ecran");
        addListToFr("feuille");
        addListToFr("envoi","expedition");
        addListToFr("qualification","competence");
        addListToFr("diapositive");
        addListToFr("logiciels");
        addListToFr("logiciel");
        addListToFr("trier");
        addListToFr("tableur");
        addListToFr("personnel");
        addListToFr("agrafe");
        addListToFr("fournitures de bureau");
        addListToFr("stocker");
        addListToFr("fournitures");
        addListToFr("reserves");
        addListToFr("sondage");
        addListToFr("panneau","clavier");
        addListToFr("embaucher");
        addListToFr("OPA");
        addListToFr("tache");
        addListToFr("interimaire");
        addListToFr("formation");
        addListToFr("mutation","muter");
        addListToFr("ordures");
        addListToFr("tendance");
        addListToFr("commande d'essai");
        addListToFr("en trois exemplaires");
        addListToFr("chiffre d'affaires");
        addListToFr("taper","dactylographier");
        addListToFr("faute de frappe");
        addListToFr("mettre a jour");
        addListToFr("poste a pourvoir");
        addListToFr("libre","a pourvoir");
        addListToFr("vacances");
        addListToFr("salaire horaire");
        addListToFr("traitement de texte");
        addListToFr("emballer");
    }
}
