package liste;

public class TransportationListe extends Liste {

    public TransportationListe() {
        super();
    }

    @Override
    public void fillEnListe() {
        addListToEn("aircraft");
        addListToEn("airline");
        addListToEn("airline ticket counter");
        addListToEn("aisle");
        addListToEn("announcement");
        addListToEn("arrival");
        addListToEn("baggage claim");
        addListToEn("board");
        addListToEn("boarding pass");
        addListToEn("book");
        addListToEn("bridge");
        addListToEn("cab");
        addListToEn("cabin");
        addListToEn("cabin attendant");
        addListToEn("call at");
        addListToEn("car");
        addListToEn("carrier");
        addListToEn("cart","trolley");
        addListToEn("check in");
        addListToEn("commute");
        addListToEn("concourse");
        addListToEn("connecting flight");
        addListToEn("connecting passenger");
        addListToEn("crew");
        addListToEn("crowded");
        addListToEn("cruising altitude");
        addListToEn("customs");
        addListToEn("delay");
        addListToEn("departure");
        addListToEn("disabled");
        addListToEn("duty-free");
        addListToEn("empty");
        addListToEn("fare");
        addListToEn("flight");
        addListToEn("flight attendant");
        addListToEn("flight deck");
        addListToEn("freight");
        addListToEn("front");
        addListToEn("full");
        addListToEn("get in");
        addListToEn("get off");
        addListToEn("jet-lag");
        addListToEn("land");
        addListToEn("landing card");
        addListToEn("lounge");
        addListToEn("luggage");
        addListToEn("luggage rack");
        addListToEn("miss");
        addListToEn("network");
        addListToEn("nonstop");
        addListToEn("on time");
        addListToEn("one-way ticket");
        addListToEn("overhead compartment");
        addListToEn("package tour");
        addListToEn("passenger");
        addListToEn("platform");
        addListToEn("proceed through gate");
        addListToEn("railroad");
        addListToEn("rear");
        addListToEn("repairs");
        addListToEn("retrieve");
        addListToEn("resume");
        addListToEn("ride");
        addListToEn("rider");
        addListToEn("return ticket","round trip ticket");
        addListToEn("route");
        addListToEn("row");
        addListToEn("runway");
        addListToEn("rush hour");
        addListToEn("schedule");
        addListToEn("seat");
        addListToEn("seatbelt");
        addListToEn("shuttle");
        addListToEn("stopover");
        addListToEn("suitcase");
        addListToEn("take off");
        addListToEn("tour");
        addListToEn("track");
        addListToEn("trip");
        addListToEn("window");
    }

    @Override
    public void fillFrListe() {
        addListToFr("avion");
        addListToFr("compagnie aerienne");
        addListToFr("comptoir d'une compagnie aerienne");
        addListToFr("couloir");
        addListToFr("annonce","avis");
        addListToFr("arrivee");
        addListToFr("lieu de recuperation des bagages");
        addListToFr("monter a bord");
        addListToFr("carte d'embarquement");
        addListToFr("reserver");
        addListToFr("pont");
        addListToFr("taxi");
        addListToFr("cabine","carlingue");
        addListToFr("membre d'equipage");
        addListToFr("faire escale");
        addListToFr("wagon");
        addListToFr("transporteur");
        addListToFr("chariot");
        addListToFr("enregistrer ses bagages");
        addListToFr("faire la navette domicile-travail");
        addListToFr("hall");
        addListToFr("vol de correspondance");
        addListToFr("passager en transit");
        addListToFr("equipage");
        addListToFr("bonde");
        addListToFr("altitude de croisiere");
        addListToFr("douane");
        addListToFr("retard");
        addListToFr("depart");
        addListToFr("hors service");
        addListToFr("hors-taxe");
        addListToFr("vide");
        addListToFr("prix du billet");
        addListToFr("vol");
        addListToFr("membre d'equipage");
        addListToFr("cabine de pilotage");
        addListToFr("fret");
        addListToFr("avant");
        addListToFr("plein");
        addListToFr("monter");
        addListToFr("descendre");
        addListToFr("decalage horaire");
        addListToFr("atterir");
        addListToFr("carte de debarquement");
        addListToFr("salon");
        addListToFr("bagages");
        addListToFr("porte-bagages");
        addListToFr("voyage organise");
        addListToFr("passager");
        addListToFr("quai de gare");
        addListToFr("se presenter a la porte n°");
        addListToFr("voie ferree");
        addListToFr("arriere");
        addListToFr("reparations");
        addListToFr("recuperer");
        addListToFr("recommencer","reprendre");
        addListToFr("trajet","voyager");
        addListToFr("passager");
        addListToFr("aller-retour");
        addListToFr("itineraire");
        addListToFr("rangee");
        addListToFr("piste");
        addListToFr("heure de pointe");
        addListToFr("horaire");
        addListToFr("siege");
        addListToFr("ceinture de securite");
        addListToFr("navette");
        addListToFr("escale");
        addListToFr("valise");
        addListToFr("decoller");
        addListToFr("voyage","excursion");
        addListToFr("voie");
        addListToFr("voyage");
        addListToFr("hublot");
    }
}
